### ISSUE TITLE
xz_file.c has a bug

### ISSUE THREAD

**Issue by wzis** [magicwolf2019/XZ_FIle#1]
In line 72-77, 
memset(fxz,0,sizeof(XZ_file_st));
so, the fxz is all 0 in bytes.
then
memset(fxz->buf_temp,0,fxz->size_buf_temp);
the fxz->size_buf_temp is not assigned, so the memset won't do what is required.

**Comment by magicwolf2019** [comment]
Hi!
Unfortunately I don't understand you.
In lines 69-71 and 74-76, the memory stands out for these variables and this is checked.

**Comment by wzis** [comment]
So the following lines:
  fxz=(XZ_file_st *)malloc(sizeof(XZ_file_st));
  if ( fxz==NULL )
    return NULL;
  memset(fxz,0,sizeof(XZ_file_st));

  fxz->buf_temp=(char *)malloc(size_buf);
  if ( fxz->buf_temp==NULL )
    goto _M_Err;
  memset(fxz->buf_temp,0,fxz->size_buf_temp);

Where did you assign a value for fxz->size_buf_temp?

**Comment by magicwolf2019** [comment]
I understood you. Thank you. I corrected the code.
